Fix profile and release activation aliases
The tna-set-profile and tna-switch-to-generation aliases now ask for
user confirmation before executing the action. The tna-set-profile
alias restarts the bfswd and bffwd processes to activate the new
profile. tna-switch-to-generation initiates a warm start to activate
the new generation.

diff --git a/scripts/set-profile b/scripts/set-profile
--- a/scripts/set-profile
+++ b/scripts/set-profile
@@ -4,11 +4,15 @@ set -e
 profile_file=$1
 profile=$2
 @CHECK_PROFILE@
-echo "Setting bf_router profile to \"$profile\""
-echo "Use"
-echo "reload warm"
-echo "or"
-echo "reload process bfswd"
-echo "reload process bffwd"
-echo "to activate"
-echo $profile >$profile_file
+current=$(cat $profile_file)
+if [ $profile == $current ]; then
+   echo "$profile is already the current profile"
+   exit 1
+fi
+read -n 1 -r  -p "Select bf_router profile \"$profile\" and reload the data-plane processes? [y/n] "
+if [[ $REPLY =~ ^[Yy]$ ]]; then
+   echo $profile >$profile_file
+   exit 0
+fi
+echo -e "\nAborting, current profile remains active"
+exit 1
diff --git a/scripts/switch-to-generation b/scripts/switch-to-generation
--- a/scripts/switch-to-generation
+++ b/scripts/switch-to-generation
@@ -3,22 +3,21 @@ set -e
 
 file=/etc/freertr/switch-to-generation
 if [ $# -eq 0 ]; then
-    if [ -e $file ]; then
-	echo "Next reload will activate generation $(cat $file)"
-    else
-	echo "No switch of generation is currently scheduled"
-    fi
-    echo "Please supply the RARE profile generation to use at the next reload"
+    echo "Please supply the RARE profile generation number you want to switch to"
     echo "Use \"tna-list-installed\" to see all currently installed generations"
-    exit 0
+    exit 1
 fi
 gen=$1
 PROFILE=@NIX_PROFILE@
 if ! [ -h $PROFILE-$gen-link ]; then
     echo "$gen is not a valid generation"
     echo "Use \"tna-list-installed\" to see all currently installed generations"
-    exit 0
+    exit 1
 fi
-echo $gen >$file
-echo "Setting RARE profile generation to $gen"
-echo "Use \"reload warm\" to activate"
+read -n 1 -r  -p "Set RARE profile generation to $gen and restart freerouter? [y/n] "
+if [[ $REPLY =~ ^[Yy]$ ]]; then
+    echo $gen >$file
+   exit 0
+fi
+echo -e "\nAborting, current profile remains active"
+exit 1
